# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'food' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for food

  target 'foodTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'food-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for food-tvOS

  target 'food-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'FBSDKLoginKit'

